const resList = [
  {
    id: "1",
    name: "KFC",
    cuisines: ["Burgers", "Biryani", "Fast Food"],
    avgRating: "3.8",
    costForTwo: "₹400 FOR TWO",
    deliveryTime: "36 minutes",
    cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
  },
  {
    id: "2",
    name: "Meghana Foods",
    cuisines: ["Biryani", "Andhra", "South Indian"],
    avgRating: "4.4",
    costForTwo: "₹500 FOR TWO",
    deliveryTime: "29 minutes",
    cloudinaryImageId: "xqwpuhgnsaf18te7zvtv",
  },
  {
    id: "3",
    name: "Empire Restaurant",
    cuisines: ["North Indian", "Kebabs"],
    avgRating: "4.1",
    costForTwo: "₹450 FOR TWO",
    deliveryTime: "25 minutes",
    cloudinaryImageId: "p3fqj6jgrebzf9hncajz",
  },
  {
    id: "4",
    name: "Burger Point",
    cuisines: ["Burgers", "Snacks", "Beverages"],
    avgRating: "3.9",
    costForTwo: "₹300 FOR TWO",
    deliveryTime: "20 minutes",
    cloudinaryImageId: "o5y4b8zslbtzxi5z0vlb",
  },
  {
    id: "5",
    name: "Pizza Palace",
    cuisines: ["Italian", "Pizza", "Pastas"],
    avgRating: "4.3",
    costForTwo: "₹600 FOR TWO",
    deliveryTime: "32 minutes",
    cloudinaryImageId: "ds8tkw0ggltg0v5fklcw",
  },
  {
    id: "6",
    name: "The Biryani House",
    cuisines: ["Hyderabadi", "South Indian"],
    avgRating: "4.0",
    costForTwo: "₹350 FOR TWO",
    deliveryTime: "28 minutes",
    cloudinaryImageId: "n5vfoznibyd7z5rzv6mn",
  },
  {
    id: "7",
    name: "Chowman",
    cuisines: ["Chinese", "Thai"],
    avgRating: "4.2",
    costForTwo: "₹450 FOR TWO",
    deliveryTime: "30 minutes",
    cloudinaryImageId: "qp8nykt6s6bqf8em0dzv",
  },
  {
    id: "8",
    name: "Thali Junction",
    cuisines: ["Gujarati", "Rajasthani", "North Indian"],
    avgRating: "4.1",
    costForTwo: "₹250 FOR TWO",
    deliveryTime: "24 minutes",
    cloudinaryImageId: "z5rbm7m7x4ce8zqswyor",
  },
  {
    id: "9",
    name: "Taco Town",
    cuisines: ["Mexican", "Fast Food"],
    avgRating: "3.7",
    costForTwo: "₹350 FOR TWO",
    deliveryTime: "22 minutes",
    cloudinaryImageId: "cwrm0z8oyh4ekno3uhgz",
  },
  {
    id: "10",
    name: "Café Brew",
    cuisines: ["Coffee", "Desserts", "Beverages"],
    avgRating: "4.5",
    costForTwo: "₹300 FOR TWO",
    deliveryTime: "18 minutes",
    cloudinaryImageId: "e4rsyttum1acxfsf8jvj",
  },
  {
    id: "11",
    name: "Saffron Spice",
    cuisines: ["North Indian", "Mughlai"],
    avgRating: "4.3",
    costForTwo: "₹500 FOR TWO",
    deliveryTime: "35 minutes",
    cloudinaryImageId: "s7wymbkk6f8ux9o6xxbc",
  },
  {
    id: "12",
    name: "Tandoori Nights",
    cuisines: ["Tandoor", "BBQ", "Indian"],
    avgRating: "4.1",
    costForTwo: "₹600 FOR TWO",
    deliveryTime: "40 minutes",
    cloudinaryImageId: "a6bzxqaxk4g9dfbs1jhr",
  },
  {
    id: "13",
    name: "Green Bowl",
    cuisines: ["Healthy Food", "Salads", "Wraps"],
    avgRating: "4.6",
    costForTwo: "₹350 FOR TWO",
    deliveryTime: "25 minutes",
    cloudinaryImageId: "v4b0zy8azrshs4vxy9xw",
  },
  {
    id: "14",
    name: "Street Adda",
    cuisines: ["Street Food", "Chaat", "Snacks"],
    avgRating: "4.0",
    costForTwo: "₹200 FOR TWO",
    deliveryTime: "20 minutes",
    cloudinaryImageId: "zogjkp4ryidfdxgcvlqe",
  },
  {
    id: "15",
    name: "Wok This Way",
    cuisines: ["Asian", "Chinese", "Thai"],
    avgRating: "4.2",
    costForTwo: "₹500 FOR TWO",
    deliveryTime: "33 minutes",
    cloudinaryImageId: "jhvvmjrb0ylfq3a3xbuw",
  },
  {
    id: "16",
    name: "Naan Stop",
    cuisines: ["Indian", "Tandoori", "Curry"],
    avgRating: "4.1",
    costForTwo: "₹400 FOR TWO",
    deliveryTime: "26 minutes",
    cloudinaryImageId: "ftmgd7khqlyznz6qmxsv",
  },
  {
    id: "17",
    name: "Momolicious",
    cuisines: ["Tibetan", "Chinese", "Snacks"],
    avgRating: "3.9",
    costForTwo: "₹300 FOR TWO",
    deliveryTime: "22 minutes",
    cloudinaryImageId: "wxvx1rr3n2ljfk3goj6j",
  },
  {
    id: "18",
    name: "Cheesy Crust",
    cuisines: ["Pizza", "Italian", "Pasta"],
    avgRating: "4.4",
    costForTwo: "₹450 FOR TWO",
    deliveryTime: "31 minutes",
    cloudinaryImageId: "uxp7z7xhn7g1uowvcx6v",
  },
  {
    id: "19",
    name: "Dosa Factory",
    cuisines: ["South Indian", "Fast Food"],
    avgRating: "4.0",
    costForTwo: "₹250 FOR TWO",
    deliveryTime: "23 minutes",
    cloudinaryImageId: "g62gyxyzt8ksz1vibf6x",
  },
  {
    id: "20",
    name: "Roll Nation",
    cuisines: ["Rolls", "Wraps", "Kebabs"],
    avgRating: "3.8",
    costForTwo: "₹200 FOR TWO",
    deliveryTime: "27 minutes",
    cloudinaryImageId: "phv2zgdhgjc2uwubz4hn",
  },
];

export default resList;
